name: Run Tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Limit Docker resources
        run: |
          docker run -d --name playwright-tests \
            --memory 2g --cpus 2 \
            -e PASSWORD="${{ secrets.PASSWORD }}" \
            -e HEADLESS_MODE="true" \
            -e TEST_ENVIRONMENT="qa" \
            -e BROWSER="chrome" \
            -p 36355:36355 \
            playwright-tests

      - name: Build the Docker image
        run: docker build -t playwright-tests -f Docker/tests.dockerfile .

      - name: Run tests and generate Allure report
        run: |
          allure_output=$(docker exec playwright-tests allure serve --port 36355 ./allure-results)

          allure_report_location=$(echo "$allure_output" | grep -oP "(?<=successfully generated to ).*")

          echo "Allure report location: $allure_report_location"
          
      - name: Copy Allure report from Docker container
        run: docker cp playwright-tests:$allure_report_location /github/workspace/allure-report

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report
