name: Run Tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build -t playwright-tests -f Docker/tests.dockerfile .

      - name: Limit Docker resources and run container
        run: |
          docker run -d --name playwright-tests \
            --memory 4g --cpus 4 \
            -e PASSWORD="${{ secrets.PASSWORD }}" \
            -e HEADLESS_MODE="true" \
            -e TEST_ENVIRONMENT="qa" \
            -e BROWSER="chrome" \
            -p 36355:36355 \
            playwright-tests

      - name: Run tests and generate Allure report
        run: |
          allure_output=$(docker exec playwright-tests allure serve --port 36355 ./allure-results)

          allure_report_location=$(echo "$allure_output" | grep -oP "(?<=successfully generated to ).*")

          echo "Allure report location: $all
