name: Run Tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest 

    resources:
      limits:
        memory: '2GB'
        cpu: 2
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build -t playwright-tests -f Docker/tests.dockerfile .

      - name: Run tests and generate Allure report
        run: |
          # Run tests in the Docker container
          container_id=$(docker run \
            -e PASSWORD="${{ secrets.PASSWORD }}" \
            -e HEADLESS_MODE="true" \
            -e TEST_ENVIRONMENT="qa" \
            -e BROWSER="chrome" \
            -p 36355:36355 \
            -d \
            playwright-tests)

          docker wait $container_id

          allure_output=$(docker exec $container_id allure serve --port 36355 ./allure-results)

          allure_report_location=$(echo "$allure_output" | grep -oP "(?<=successfully generated to ).*")

          echo "Allure report location: $allure_report_location"

      - name: Copy Allure report from Docker container
        run: docker cp $container_id:$allure_report_location /github/workspace/allure-report

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: allure-report
