name: Run Tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build -t playwright-tests -f Docker/tests.dockerfile .

      - name: Run tests
        run: |
          docker run -d \
            -e PASSWORD="${{ secrets.PASSWORD }}" \
            -e HEADLESS_MODE="true" \
            -e TEST_ENVIRONMENT="qa" \
            -e BROWSER="chrome" \
            -p 36355:36355 \
            playwright-tests
          # Assuming Allure reports are generated in a directory named 'allure-results'
          # You need to copy the generated reports to a directory accessible by GitHub Actions
          cp -r allure-results $GITHUB_WORKSPACE/allure-results

      - name: Upload Allure reports as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: allure-reports
          path: $GITHUB_WORKSPACE/allure-results
