name: Run Tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build -t playwright-tests -f Docker/tests.dockerfile .

      - name: Run tests
        run: |
          docker run -d \
            -e PASSWORD="${{ secrets.PASSWORD }}" \
            -e HEADLESS_MODE="true" \
            -e TEST_ENVIRONMENT="qa" \
            -e BROWSER="chrome" \
            -p 36355:36355 \
            playwright-tests
          # Constructing URL for Allure reports
          echo "Allure reports are being served at ${{ github.server_url }}:36355"

  ngrok:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: Set up ngrok
        uses: martinfrancois/setup-ngrok@v1
        with:
          authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start ngrok
        run: |
          ngrok http 36355 > /dev/null &  # Start ngrok in the background
          sleep 10  # Wait for ngrok to establish the tunnel

      - name: Get ngrok URL
        run: echo "Ngrok URL: ${{ steps.ngrok.outputs.url }}"
