name: Run Tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stop and remove all containers
        run: |
          docker stop $(docker ps -q) || true
          docker rm $(docker ps -aq) || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build -t playwright-tests -f Docker/tests.dockerfile .

      - name: Limit Docker resources and run container
        run: |
          docker run -d --name playwright-tests \
            --memory 8g \
            -e PASSWORD="${{ secrets.PASSWORD }}" \
            -e HEADLESS_MODE="true" \
            -e TEST_ENVIRONMENT="qa" \
            -e BROWSER="chrome" \
            -p 36355:36355 \
            playwright-tests

      - name: Check Port Connectivity
        run: |
          telnet localhost 36355

      - name: Get Docker container IP address
        id: container-ip
        run: |
          container_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' playwright-tests)
          echo "::set-output name=container_ip::$container_ip"

      - name: Debug Docker container logs
        run: docker logs playwright-tests

      - name: Echo Allure report URL
        run: |
          container_ip=${{ steps.container-ip.outputs.container_ip }}
          allure_report_url="http://$container_ip:36355"
          echo "Allure report is available at $allure_report_url"

      - name: Wait for Allure report to be available
        run: |
          container_ip=${{ steps.container-ip.outputs.container_ip }}
          allure_report_url="http://$container_ip:36355"
          until curl -sSf "$allure_report_url" >/dev/null; do
            echo "Waiting for Allure report to be available..."
            sleep 10
          done

      - name: Fetch Allure report from Docker container
        run: |
          container_ip=${{ steps.container-ip.outputs.container_ip }}
          allure_report=$(curl -sS "http://${container_ip}:36355")
          echo "$allure_report"

      - name: Deploy Allure report to Netlify
        run: |
          netlify deploy --prod --dir=allure-report.html
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Display Netlify URL
        run: |
          netlify_url=$(netlify status | grep "Website URL" | awk '{print $3}')
          echo "Netlify deployment is available at $netlify_url"          