name: Run Tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build -t playwright-tests -f Docker/tests.dockerfile .

      - name: Run tests
        run: |
          docker run -d \
            -e PASSWORD="${{ secrets.PASSWORD }}" \
            -e HEADLESS_MODE="true" \
            -e TEST_ENVIRONMENT="qa" \
            -e BROWSER="chrome" \
            -p 36355:36355 \
            playwright-tests

          sleep 10

          if [ -d "allure-results" ]; then
            cp -r allure-results/* $GITHUB_WORKSPACE/allure-reports/
          else
            echo "Allure reports directory not found."
          fi

      - name: Upload Allure reports as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: allure-reports
          path: $GITHUB_WORKSPACE/allure-reports
