name: Run Tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Stop and remove all containers
        run: |
          docker stop $(docker ps -q) || true
          docker rm $(docker ps -aq) || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build -t playwright-tests -f Docker/tests.dockerfile .

      - name: Run Docker container
        id: run-container
        run: |
          docker run -d --name playwright-tests \
            --memory 8g \
            -e PASSWORD="${{ secrets.PASSWORD }}" \
            -e HEADLESS_MODE="true" \
            -e TEST_ENVIRONMENT="qa" \
            -e BROWSER="chrome" \
            -p 5050:5050 \
            playwright-tests

      - name: Wait for Docker container to start
        run: sleep 10

      - name: Find Allure report directory
        id: find-allure-directory
        run: |
          container_id=$(docker ps -qf "name=playwright-tests")
          allure_directory=$(docker exec $container_id find /tmp -type d -name "allure-report" -print -quit)
          echo "::set-output name=allure_directory::$allure_directory"

      - name: Copy Allure report out of Docker container
        run: |
          container_id=$(docker ps -qf "name=playwright-tests")
          allure_directory=$(echo "${{ steps.find-allure-directory.outputs.allure_directory }}")
          docker cp $container_id:$allure_directory ./allure-results

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './allure-results'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
