name: Run Tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok
          sudo mv ngrok /usr/local/bin/ngrok

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build -t playwright-tests -f Docker/tests.dockerfile .

      - name: Start ngrok
        run: |
          ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ./ngrok http 36355 > /dev/null &
          sleep 10  # Wait for ngrok to establish the tunnel

      - name: Run tests
        run: |
          # Run tests in the Docker container
          docker run -d \
            -e PASSWORD="${{ secrets.PASSWORD }}" \
            -e HEADLESS_MODE="true" \
            -e TEST_ENVIRONMENT="qa" \
            -e BROWSER="chrome" \
            playwright-tests

      - name: Upload Allure reports as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: allure-reports
          path: $GITHUB_WORKSPACE/allure-reports
